/*
 * @author dacs0
 * @version 1.2
 * @since
 * ITSC1213 156
 */
package lab9storybook;

/**
 * This is the End Frame for the GUI
 * @author dacs0
 */
public class EndFrame extends javax.swing.JFrame {

	private StorybookModel myModel;
	/**
	 * Creates new form EndFrame using storybook model parameter
	 */
	public EndFrame(StorybookModel myModel) {
		this.myModel = myModel;
		initComponents();
		welcomeLabel.setText("Welcome, " + myModel.getUserName() + ".");
		crimeLabel.setText("You have been accused of " + myModel.getCrime() + ".");
		instructionLabel.setText("Pick a door to determine your verdict.");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      welcomeLabel = new javax.swing.JLabel();
      crimeLabel = new javax.swing.JLabel();
      instructionLabel = new javax.swing.JLabel();
      leftDoorButton = new javax.swing.JButton();
      rightDoorButton = new javax.swing.JButton();
      exitTribunal = new javax.swing.JButton();
      nextTrial = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      welcomeLabel.setText("Welcome");

      crimeLabel.setText("Crime accused");

      instructionLabel.setText("Door");

      leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/StoryBookGIFs/Door.GIF"))); // NOI18N
      leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            leftDoorButtonActionPerformed(evt);
         }
      });

      rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/StoryBookGIFs/Door.GIF"))); // NOI18N
      rightDoorButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rightDoorButtonActionPerformed(evt);
         }
      });

      exitTribunal.setText("Exit Tribunal");
      exitTribunal.setEnabled(false);
      exitTribunal.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitTribunalActionPerformed(evt);
         }
      });

      nextTrial.setText("Next Trial -->");
      nextTrial.setEnabled(false);
      nextTrial.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            nextTrialActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(leftDoorButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
            .addComponent(rightDoorButton)
            .addGap(46, 46, 46))
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(instructionLabel)
                     .addComponent(crimeLabel)
                     .addComponent(welcomeLabel))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(exitTribunal)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(nextTrial)
                  .addGap(26, 26, 26))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(crimeLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(instructionLabel)
            .addGap(41, 41, 41)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(leftDoorButton)
               .addComponent(rightDoorButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(exitTribunal)
               .addComponent(nextTrial))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed
      // if the left door is selected, the right door is invisible and more buttons appear.
		rightDoorButton.setEnabled(false);
		leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/StoryBookGIFs/Tiger.GIF"))); // NOI18N
      instructionLabel.setText("You are GUILTY! Prepare to be eaten!");
		
		leftDoorButton.setEnabled(rootPaneCheckingEnabled);
		exitTribunal.setEnabled(true);
		nextTrial.setEnabled(true);
   }//GEN-LAST:event_leftDoorButtonActionPerformed

   private void rightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorButtonActionPerformed
      // if the right door is selected, the left door is invisible and more buttons appear.
		leftDoorButton.setEnabled(false);
		rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/StoryBookGIFs/Lady.GIF"))); // NOI18N
     
		instructionLabel.setText("You are INNOCENT! Sorry about that. Please accept this lady.");
		exitTribunal.setEnabled(true);
		nextTrial.setEnabled(true);
   }//GEN-LAST:event_rightDoorButtonActionPerformed

   private void nextTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrialActionPerformed
      // Starts a new trial once the next trial button is pushed.
		StartFrame newStartFrame = new StartFrame(myModel);
		newStartFrame.setVisible(true);
		this.dispose();
   }//GEN-LAST:event_nextTrialActionPerformed

   private void exitTribunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTribunalActionPerformed
      // Exits the tribunal
		System.exit(0);
   }//GEN-LAST:event_exitTribunalActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel crimeLabel;
   private javax.swing.JButton exitTribunal;
   private javax.swing.JLabel instructionLabel;
   private javax.swing.JButton leftDoorButton;
   private javax.swing.JButton nextTrial;
   private javax.swing.JButton rightDoorButton;
   private javax.swing.JLabel welcomeLabel;
   // End of variables declaration//GEN-END:variables
}
